### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by michaeljota** [michaeljota/angular2-ultimate-starter#1]
- [ ] SASS Support (wip)
- [ ] Bootstrap support (wip)
- [ ] Bootstrap theming (see: [material2#theming](https://github.com/angular/material2/blob/master/docs/theming.md))
- [ ] [`material2`](https://github.com/angular/material2) 
- [ ] [`primeng`](http://www.primefaces.org/primeng/)
- [ ] Aditional tslint rules from [`vrsource-tslint-rules`](https://www.npmjs.com/package/vrsource-tslint-rules) and [`tslint-eslint-rules`](https://www.npmjs.com/package/tslint-eslint-rules)

v 0.0.1
- [x] launch
